// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Borentra.Email.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\jamie_000\Documents\GitHub\Borentra-BeastMode\Borentra\Email\Template\GenericTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class GenericTemplate : GenericTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.or" +
                    "g/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html>\r\n<head>\r\n    <title>");
            
            #line 9 "C:\Users\jamie_000\Documents\GitHub\Borentra-BeastMode\Borentra\Email\Template\GenericTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write("</title>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">" +
                    "\r\n    <meta name=\"viewport\" content=\"width=320, target-densitydpi=device-dpi\">\r\n" +
                    "    <style type=\"text/css\">\r\n        /* Mobile-specific Styles */\r\n        @medi" +
                    "a only screen and (max-width: 660px) {\r\n            table[class=w0], td[class=w0" +
                    "] {\r\n                width: 0 !important;\r\n            }\r\n\r\n            table[cl" +
                    "ass=w10], td[class=w10], img[class=w10] {\r\n                width: 5px !important" +
                    ";\r\n            }\r\n\r\n            table[class=w15], td[class=w15], img[class=w15] " +
                    "{\r\n                width: 5px !important;\r\n            }\r\n\r\n            table[cl" +
                    "ass=w30], td[class=w30], img[class=w30] {\r\n                width: 10px !importan" +
                    "t;\r\n            }\r\n\r\n            table[class=w60], td[class=w60], img[class=w60]" +
                    " {\r\n                width: 10px !important;\r\n            }\r\n\r\n            table[" +
                    "class=w125], td[class=w125], img[class=w125] {\r\n                width: 80px !imp" +
                    "ortant;\r\n            }\r\n\r\n            table[class=w130], td[class=w130], img[cla" +
                    "ss=w130] {\r\n                width: 55px !important;\r\n            }\r\n\r\n          " +
                    "  table[class=w140], td[class=w140], img[class=w140] {\r\n                width: 9" +
                    "0px !important;\r\n            }\r\n\r\n            table[class=w160], td[class=w160]," +
                    " img[class=w160] {\r\n                width: 180px !important;\r\n            }\r\n\r\n " +
                    "           table[class=w170], td[class=w170], img[class=w170] {\r\n               " +
                    " width: 100px !important;\r\n            }\r\n\r\n            table[class=w180], td[cl" +
                    "ass=w180], img[class=w180] {\r\n                width: 80px !important;\r\n         " +
                    "   }\r\n\r\n            table[class=w195], td[class=w195], img[class=w195] {\r\n      " +
                    "          width: 80px !important;\r\n            }\r\n\r\n            table[class=w220" +
                    "], td[class=w220], img[class=w220] {\r\n                width: 80px !important;\r\n " +
                    "           }\r\n\r\n            table[class=w240], td[class=w240], img[class=w240] {" +
                    "\r\n                width: 180px !important;\r\n            }\r\n\r\n            table[c" +
                    "lass=w255], td[class=w255], img[class=w255] {\r\n                width: 185px !imp" +
                    "ortant;\r\n            }\r\n\r\n            table[class=w275], td[class=w275], img[cla" +
                    "ss=w275] {\r\n                width: 135px !important;\r\n            }\r\n\r\n         " +
                    "   table[class=w280], td[class=w280], img[class=w280] {\r\n                width: " +
                    "135px !important;\r\n            }\r\n\r\n            table[class=w300], td[class=w300" +
                    "], img[class=w300] {\r\n                width: 140px !important;\r\n            }\r\n\r" +
                    "\n            table[class=w325], td[class=w325], img[class=w325] {\r\n             " +
                    "   width: 95px !important;\r\n            }\r\n\r\n            table[class=w360], td[c" +
                    "lass=w360], img[class=w360] {\r\n                width: 140px !important;\r\n       " +
                    "     }\r\n\r\n            table[class=w410], td[class=w410], img[class=w410] {\r\n    " +
                    "            width: 180px !important;\r\n            }\r\n\r\n            table[class=w" +
                    "470], td[class=w470], img[class=w470] {\r\n                width: 200px !important" +
                    ";\r\n            }\r\n\r\n            table[class=w580], td[class=w580], img[class=w58" +
                    "0] {\r\n                width: 280px !important;\r\n            }\r\n\r\n            tab" +
                    "le[class=w640], td[class=w640], img[class=w640] {\r\n                width: 300px " +
                    "!important;\r\n            }\r\n\r\n            table[class*=hide], td[class*=hide], i" +
                    "mg[class*=hide], p[class*=hide], span[class*=hide] {\r\n                display: n" +
                    "one !important;\r\n            }\r\n\r\n            table[class=h0], td[class=h0] {\r\n " +
                    "               height: 0 !important;\r\n            }\r\n\r\n            p[class=foote" +
                    "r-content-left] {\r\n                text-align: center !important;\r\n            }" +
                    "\r\n\r\n            #headline p {\r\n                font-size: 30px !important;\r\n    " +
                    "        }\r\n\r\n            .article-content, #left-sidebar {\r\n                -web" +
                    "kit-text-size-adjust: 90% !important;\r\n                -ms-text-size-adjust: 90%" +
                    " !important;\r\n            }\r\n\r\n            .header-content, .footer-content-left" +
                    " {\r\n                -webkit-text-size-adjust: 80% !important;\r\n                -" +
                    "ms-text-size-adjust: 80% !important;\r\n            }\r\n\r\n            img {\r\n      " +
                    "          height: auto;\r\n                line-height: 100%;\r\n            }\r\n    " +
                    "    }\r\n        /* Client-specific Styles */\r\n        #outlook a {\r\n            p" +
                    "adding: 0;\r\n        }\r\n        /* Force Outlook to provide a \"view in browser\" b" +
                    "utton. */\r\n        body {\r\n            width: 100% !important;\r\n        }\r\n\r\n   " +
                    "     .ReadMsgBody {\r\n            width: 100%;\r\n        }\r\n\r\n        .ExternalCla" +
                    "ss {\r\n            width: 100%;\r\n            display: block !important;\r\n        " +
                    "}\r\n        /* Force Hotmail to display emails at full width */\r\n        /* Reset" +
                    " Styles */\r\n        /* Add 100px so mobile switch bar doesn\'t cover street addre" +
                    "ss. */\r\n        body {\r\n            background-color: #ececec;\r\n            marg" +
                    "in: 0;\r\n            padding: 0;\r\n        }\r\n\r\n        img {\r\n            outline" +
                    ": none;\r\n            text-decoration: none;\r\n            display: block;\r\n      " +
                    "  }\r\n\r\n        br, strong br, b br, em br, i br {\r\n            line-height: 100%" +
                    ";\r\n        }\r\n\r\n        h1, h2, h3, h4, h5, h6 {\r\n            line-height: 100% " +
                    "!important;\r\n            -webkit-font-smoothing: antialiased;\r\n        }\r\n\r\n    " +
                    "        h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {\r\n                color: blue !impor" +
                    "tant;\r\n            }\r\n\r\n                h1 a:active, h2 a:active, h3 a:active, h" +
                    "4 a:active, h5 a:active, h6 a:active {\r\n                    color: red !importan" +
                    "t;\r\n                }\r\n                /* Preferably not the same color as the n" +
                    "ormal header link color.  There is limited support for psuedo classes in email c" +
                    "lients, this was added just for good measure. */\r\n                h1 a:visited, " +
                    "h2 a:visited, h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {\r\n        " +
                    "            color: purple !important;\r\n                }\r\n        /* Preferably " +
                    "not the same color as the normal header link color. There is limited support for" +
                    " psuedo classes in email clients, this was added just for good measure. */\r\n    " +
                    "    table td, table tr {\r\n            border-collapse: collapse;\r\n        }\r\n\r\n " +
                    "       .yshortcuts, .yshortcuts a, .yshortcuts a:link, .yshortcuts a:visited, .y" +
                    "shortcuts a:hover, .yshortcuts a span {\r\n            color: black;\r\n            " +
                    "text-decoration: none !important;\r\n            border-bottom: none !important;\r\n" +
                    "            background: none !important;\r\n        }\r\n        /* Body text color " +
                    "for the New Yahoo.  This example sets the font of Yahoo\'s Shortcuts to black. */" +
                    "\r\n        /* This most probably won\'t work in all email clients. Don\'t include c" +
                    "ode blocks in email. */\r\n        code {\r\n            white-space: normal;\r\n     " +
                    "       word-break: break-all;\r\n        }\r\n\r\n        #background-table {\r\n       " +
                    "     background-color: #ececec;\r\n        }\r\n        /* Webkit Elements */\r\n     " +
                    "   #top-bar {\r\n            border-radius: 6px 6px 0px 0px;\r\n            -moz-bor" +
                    "der-radius: 6px 6px 0px 0px;\r\n            -webkit-border-radius: 6px 6px 0px 0px" +
                    ";\r\n            -webkit-font-smoothing: antialiased;\r\n            background-colo" +
                    "r: #322d4d;\r\n            color: #5f5170;\r\n        }\r\n\r\n            #top-bar a {\r" +
                    "\n                font-weight: bold;\r\n                text-decoration: none;\r\n   " +
                    "         }\r\n\r\n        #footer {\r\n            border-radius: 0px 0px 6px 6px;\r\n  " +
                    "          -moz-border-radius: 0px 0px 6px 6px;\r\n            -webkit-border-radiu" +
                    "s: 0px 0px 6px 6px;\r\n            -webkit-font-smoothing: antialiased;\r\n        }" +
                    "\r\n        /* Fonts and Content */\r\n        body, td {\r\n            font-family: " +
                    "\'Helvetica Neue\', Arial, Helvetica, Geneva, sans-serif;\r\n        }\r\n\r\n        .h" +
                    "eader-content, .footer-content-left, .footer-content-right {\r\n            -webki" +
                    "t-text-size-adjust: none;\r\n            -ms-text-size-adjust: none;\r\n        }\r\n " +
                    "       /* Prevent Webkit and Windows Mobile platforms from changing default font" +
                    " sizes on header and footer. */\r\n        .header-content {\r\n            font-siz" +
                    "e: 12px;\r\n            color: #5f5170;\r\n        }\r\n\r\n            .header-content " +
                    "a {\r\n                font-weight: bold;\r\n                text-decoration: none;\r" +
                    "\n            }\r\n\r\n        #headline p {\r\n            color: #f2e9a8;\r\n          " +
                    "  font-family: \'Helvetica Neue\', Arial, Helvetica, Geneva, sans-serif;\r\n        " +
                    "    font-size: 36px;\r\n            text-align: center;\r\n            margin-top: 0" +
                    "px;\r\n            margin-bottom: 30px;\r\n        }\r\n\r\n            #headline p a {\r" +
                    "\n                color: #f2e9a8;\r\n                text-decoration: none;\r\n      " +
                    "      }\r\n\r\n        .article-title {\r\n            font-size: 18px;\r\n            l" +
                    "ine-height: 24px;\r\n            font-weight: bold;\r\n            margin-top: 0px;\r" +
                    "\n            margin-bottom: 18px;\r\n            font-family: \'Helvetica Neue\', Ar" +
                    "ial, Helvetica, Geneva, sans-serif;\r\n        }\r\n\r\n            .article-title a {" +
                    "\r\n                text-decoration: none;\r\n            }\r\n\r\n            .article-" +
                    "title.with-meta {\r\n                margin-bottom: 0;\r\n            }\r\n\r\n        ." +
                    "article-meta {\r\n            font-size: 13px;\r\n            line-height: 20px;\r\n  " +
                    "          color: #ccc;\r\n            font-weight: bold;\r\n            margin-top: " +
                    "0;\r\n        }\r\n\r\n        .article-content {\r\n            font-size: 13px;\r\n     " +
                    "       line-height: 18px;\r\n            color: #666666;\r\n            margin-top: " +
                    "0px;\r\n            margin-bottom: 18px;\r\n            font-family: \'Helvetica Neue" +
                    "\', Arial, Helvetica, Geneva, sans-serif;\r\n        }\r\n\r\n            .article-cont" +
                    "ent a {\r\n                font-weight: bold;\r\n                text-decoration: no" +
                    "ne;\r\n            }\r\n\r\n            .article-content img {\r\n                max-wi" +
                    "dth: 100%;\r\n            }\r\n\r\n            .article-content ol, .article-content u" +
                    "l {\r\n                margin-top: 0px;\r\n                margin-bottom: 18px;\r\n   " +
                    "             margin-left: 19px;\r\n                padding: 0;\r\n            }\r\n\r\n " +
                    "           .article-content li {\r\n                font-size: 13px;\r\n            " +
                    "    line-height: 18px;\r\n                color: #666666;\r\n            }\r\n\r\n      " +
                    "          .article-content li a {\r\n                    text-decoration: underlin" +
                    "e;\r\n                }\r\n\r\n            .article-content p {\r\n                margi" +
                    "n-bottom: 15px;\r\n            }\r\n\r\n        .footer-content-left {\r\n            fo" +
                    "nt-size: 12px;\r\n            line-height: 15px;\r\n            color: #826fa6;\r\n   " +
                    "         margin-top: 0px;\r\n            margin-bottom: 15px;\r\n        }\r\n\r\n      " +
                    "      .footer-content-left a {\r\n                font-weight: bold;\r\n            " +
                    "    text-decoration: none;\r\n            }\r\n\r\n        .footer-content-right {\r\n  " +
                    "          font-size: 11px;\r\n            line-height: 16px;\r\n            color: #" +
                    "826fa6;\r\n            margin-top: 0px;\r\n            margin-bottom: 15px;\r\n       " +
                    " }\r\n\r\n            .footer-content-right a {\r\n                font-weight: bold;\r" +
                    "\n                text-decoration: none;\r\n            }\r\n\r\n        #footer {\r\n   " +
                    "         background-color: #322d4d;\r\n            color: #826fa6;\r\n        }\r\n\r\n " +
                    "           #footer a {\r\n                text-decoration: none;\r\n                " +
                    "font-weight: bold;\r\n            }\r\n\r\n        #permission-reminder {\r\n           " +
                    " white-space: normal;\r\n        }\r\n\r\n        #street-address {\r\n            white" +
                    "-space: normal;\r\n        }\r\n\r\n        a.nav-brand {\r\n            text-decoration" +
                    ": none;\r\n            float: left;\r\n            display: block;\r\n            colo" +
                    "r: #ffffff;\r\n            width: 150px;\r\n            background: transparent url(" +
                    "http://cdn.borentra.com/assets/img/ui/logo-borentra-45x45.png) 0 15px no-repeat;" +
                    "\r\n            margin-left: 0px;\r\n            padding-right: 0px;\r\n            he" +
                    "ight: 43px;\r\n            -webkit-transition: background-position 400ms ease;\r\n  " +
                    "      }\r\n\r\n            a.nav-brand:hover {\r\n                text-decoration: non" +
                    "e;\r\n                color: #f0f0f0;\r\n                background-position: 0 0px;" +
                    "\r\n            }\r\n\r\n            a.nav-brand span {\r\n                font-size: 22" +
                    "px;\r\n                text-shadow: 0px 1px 1px #333;\r\n                display: bl" +
                    "ock;\r\n                letter-spacing: -1px;\r\n                font-weight: bold;\r" +
                    "\n                padding-left: 38px;\r\n                padding-top: 5px;\r\n       " +
                    "     }\r\n    </style>\r\n    <!--[if gte mso 9]>\r\n    <style _tmplitem=\"2498\" >\r\n  " +
                    "  .article-content ol, .article-content ul {\r\n       margin: 0 0 0 24px;\r\n      " +
                    " padding: 0;\r\n       list-style-position: inside;\r\n    }\r\n    </style>\r\n    <![e" +
                    "ndif]-->\r\n</head>\r\n<body>\r\n    <table width=\"100%\" cellpadding=\"0\" cellspacing=\"" +
                    "0\" border=\"0\" id=\"background-table\">\r\n        <tbody>\r\n            <tr>\r\n       " +
                    "         <td align=\"center\" bgcolor=\"#ececec\">\r\n                    <table class" +
                    "=\"w640\" style=\"margin: 0 10px;\" width=\"640\" cellpadding=\"0\" cellspacing=\"0\" bord" +
                    "er=\"0\">\r\n                        <tbody>\r\n                            <tr>\r\n    " +
                    "                            <td class=\"w640\" width=\"640\" height=\"20\"></td>\r\n    " +
                    "                        </tr>\r\n\r\n                            <tr>\r\n             " +
                    "                   <td id=\"header\" class=\"w640\" width=\"640\" align=\"center\" bgcol" +
                    "or=\"#e55445\">\r\n\r\n                                    <div align=\"center\" style=\"" +
                    "text-align: center\">\r\n                                        <a href=\"http://ww" +
                    "w.borentra.com?utm_source=header&utm_campaign=share&utm_medium=email\" class=\"nav" +
                    "-brand\" title=\"Borentra: Borrow, Rent, Trade\">\r\n                                " +
                    "            <span style=\"color:#fff;font-size:x-large;text-decoration:none\">Bore" +
                    "ntra</span>\r\n                                        </a>\r\n                     " +
                    "               </div>\r\n                                </td>\r\n                  " +
                    "          </tr>\r\n\r\n                            <tr>\r\n                           " +
                    "     <td class=\"w640\" width=\"640\" height=\"30\" bgcolor=\"#ffffff\"></td>\r\n         " +
                    "                   </tr>\r\n                            <tr id=\"gallery-content-ro" +
                    "w\">\r\n                                <td class=\"w640\" width=\"640\" bgcolor=\"#ffff" +
                    "ff\">\r\n                                    <table class=\"w640\" width=\"640\" cellpa" +
                    "dding=\"0\" cellspacing=\"0\" border=\"0\">\r\n                                        <" +
                    "tbody>\r\n                                            <tr>\r\n                      " +
                    "                          <td class=\"w30\" width=\"30\"></td>\r\n                    " +
                    "                            <td class=\"w580\" width=\"580\">\r\n                     " +
                    "                               <repeater>\r\n\r\n\r\n                                 " +
                    "                       <layout label=\"Text only\">\r\n                             " +
                    "                               <table class=\"w580\" width=\"580\" cellpadding=\"0\" c" +
                    "ellspacing=\"0\" border=\"0\">\r\n                                                    " +
                    "            <tbody>\r\n                                                           " +
                    "         <tr>\r\n                                                                 " +
                    "       <td class=\"w580\" width=\"580\">\r\n                                          " +
                    "                                  <p align=\"left\" class=\"article-title\">\r\n      " +
                    "                                                                          <singl" +
                    "eline label=\"Title\">\r\n                                                          " +
                    "                          ");
            
            #line 459 "C:\Users\jamie_000\Documents\GitHub\Borentra-BeastMode\Borentra\Email\Template\GenericTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Title));
            
            #line default
            #line hidden
            this.Write(@"
                                                                                </singleline>
                                                                            </p>
                                                                            <div align=""left"" class=""article-content"">
                                                                                <multiline label=""Description"">
                                                                                    ");
            
            #line 464 "C:\Users\jamie_000\Documents\GitHub\Borentra-BeastMode\Borentra\Email\Template\GenericTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Body));
            
            #line default
            #line hidden
            this.Write("\r\n                                                                               " +
                    " </multiline>\r\n                                                                 " +
                    "           </div>\r\n                                                             " +
                    "               <hr />\r\n                                                         " +
                    "                   <table>\r\n                                                    " +
                    "                            <tr>\r\n                                              " +
                    "                                      <td>\r\n                                    " +
                    "                                                    <a href=\"https://www.faceboo" +
                    "k.com/Borentra\" target=\"_blank\" rel=\"publisher\">\r\n                              " +
                    "                                                              <img src=\"http://c" +
                    "dn.borentra.com/assets/img/facebook_small.jpg\" title=\"Join us on Facebook\" heigh" +
                    "t=\"40px\" />\r\n                                                                   " +
                    "                     </a>\r\n                                                     " +
                    "                               </td>\r\n                                          " +
                    "                                          <td>\r\n                                " +
                    "                                                        <a href=\"https://twitter" +
                    ".com/Borentra\" target=\"_blank\" rel=\"publisher\">\r\n                               " +
                    "                                                             <img src=\"http://cd" +
                    "n.borentra.com/assets/img/twitter_logo.jpg\" title=\"Follow us on Twitter\" height=" +
                    "\"40px\" />\r\n                                                                     " +
                    "                   </a>\r\n                                                       " +
                    "                             </td>\r\n                                            " +
                    "                                        <td>\r\n                                  " +
                    "                                                      <a href=\"https://plus.goog" +
                    "le.com/106550752085264387024\" target=\"_blank\" rel=\"publisher\">\r\n                " +
                    "                                                                            <img" +
                    " src=\"http://cdn.borentra.com/assets/img/google_plus.png\" title=\"Join us on Goog" +
                    "le Plus\" height=\"40px\" />\r\n                                                     " +
                    "                                   </a>\r\n                                       " +
                    "                                             </td>\r\n                            " +
                    "                                                        <td>\r\n                  " +
                    "                                                                      <a href=\"h" +
                    "ttp://instagram.com/borentragram\" target=\"_blank\" rel=\"publisher\">\r\n            " +
                    "                                                                                " +
                    "<img src=\"http://cdn.borentra.com/assets/img/instagram.jpg\" title=\"Join us on In" +
                    "stagram\" height=\"40px\" />\r\n                                                     " +
                    "                                   </a>\r\n                                       " +
                    "                                             </td>\r\n                            " +
                    "                                                        <td>\r\n                  " +
                    "                                                                      <a href=\"h" +
                    "ttp://borentra.tumblr.com\" target=\"_blank\" rel=\"publisher\">\r\n                   " +
                    "                                                                         <img sr" +
                    "c=\"http://cdn.borentra.com/assets/img/tumblr.png\" title=\"Join us on Tumblr\" heig" +
                    "ht=\"40px\" />\r\n                                                                  " +
                    "                      </a>\r\n                                                    " +
                    "                                </td>\r\n                                         " +
                    "                                       </tr>\r\n                                  " +
                    "                                          </table>\r\n                            " +
                    "                                                <hr>\r\n                          " +
                    "                                                  <font size=\"0\" color=\"#bbb\">\r\n" +
                    "                                                                                " +
                    "<p id=\"permission-reminder\" align=\"left\" class=\"footer-content-left\">\r\n         " +
                    "                                                                           You\'r" +
                    "e receiving this because you are a valued member of the Borentra sharing communi" +
                    "ty; to unsubscribe follow this <a style=\"font-size:xx-small;color:grey\" href=\"%u" +
                    "nsubscribe_url%\">link</a>.\r\n                                                    " +
                    "                                <br />\r\n                                        " +
                    "                                            Please don\'t mark us as spam, as it " +
                    "prevents other Borentra members from getting in touch with one another.\r\n       " +
                    "                                                                         </p>\r\n " +
                    "                                                                           </fon" +
                    "t>\r\n                                                                        </td" +
                    ">\r\n                                                                    </tr>\r\n  " +
                    "                                                                  <tr><td class=" +
                    "\"w580\" width=\"580\" height=\"10\"></td></tr>\r\n                                     " +
                    "                           </tbody>\r\n                                           " +
                    "                 </table>\r\n                                                     " +
                    "   </layout>\r\n                                                    </repeater>\r\n " +
                    "                                               </td>\r\n                          " +
                    "                      <td class=\"w30\" width=\"30\"></td>\r\n                        " +
                    "                    </tr>\r\n                                        </tbody>\r\n   " +
                    "                                 </table>\r\n                                </td>" +
                    "\r\n                            </tr>\r\n                            <tr>\r\n         " +
                    "                       <td class=\"w640\" width=\"640\" height=\"15\" bgcolor=\"#ffffff" +
                    "\"></td>\r\n                            </tr>\r\n                        </tbody>\r\n  " +
                    "                  </table>\r\n                </td>\r\n            </tr>\r\n        </" +
                    "tbody>\r\n    </table>\r\n</body>\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class GenericTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
